name: Type Annotations Check

on:
  pull_request:

jobs:
  mypy-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install -E mypy

    - name: Run mypy
      run: poetry run mypy
